
import { Toaster } from "react-hot-toast";
import Providers from "./components/Provider";
import "./globals.css";



export const metadata = {
  title: "Virtual Arena",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">

      <body>
        <Providers>
          <Toaster position="top-right" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
